version: '3'

services: 
    app:
        image: webdevops/php-apache-dev:7.4
        volumes:
            - ./app:/app
        ports:
            - 8000:80
        env_file: 
            - .env
        environment: 
            - 'WEB_DOCUMENT_ROOT=/app/public'
        networks:
            - symfony

networks:
    symfony: